#!/bin/bash

cd "$(dirname -- "$0")/.."
VENV="$(basename $PWD).venv"

echo "==> Preparing dependencies..."

PY_VERSION=$PYENV_VERSION
pyenv install --skip--existing "$PY_VERSION"

test -d $VENV || python -m venv $VENV || {
	echo "==>Failed to find/create a virtualenv"
	exit 1
    }

source $VENV/bin/activate

eval "$(pyenv init --path)"
pip install numpy
pip install matplotlib
